--create Notifications table
create table notifications (
  id bigint generated by default as identity primary key,
  user_id text NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  body text NOT NULL,
  card_id bigint REFERENCES cards (id) ON DELETE CASCADE,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
-- Create trigger function for notifications
create or replace function notify_user ()
returns trigger
language plpgsql
security definer
as $$
begin
  if new.assigned_to <> old.assigned_to then
    insert into notifications (user_id, body, card_id)
    values (new.assigned_to, 'You have been assigned to a card!', new.id);
  end if;
  return new;
end;
$$;

-- trigger the function every time a board is created
create trigger on_card_assigned
  before update on cards
  for each row execute procedure notify_user();

-- notifications row level security
alter table notifications enable row level security;